package com.smartherd.smartmart.utils

object Constants {
    const val ID: String = "id"
    const val INTENT_USER_ID: String = "user_id"
    const val USERS: String = "users"
    const val FARMERS: String = "farmers"
    const val CUSTOMERS: String = "customers"
    const val IMAGE: String = "image"
    const val NAME: String = "name"
    const val MOBILE: String = "mobile"
    const val ROLE: String = "role"
    const val LOCATION: String = "location"
    const val LONGITUDE: String = "longitude"
    const val LATITUDE : String = "latitude"
    const val AVERAGE_LOCATION: String = "average_location"
    const val CEREALS: String = "Cereals"
    const val MEAT: String = "Meat"
    const val DAIRY: String = "Dairy"
    const val GREENSANDVEGETABLES: String = "Greens and Vegetables"
    const val OTHER: String = "Other Farm Products"
    const val PRODUCTS: String = "products"
    const val PRODUCT_NAME: String = "productName"
    const val PRODUCT_DESCRIPTION: String = "productDescription"
    const val PRODUCT_CATEGORY: String = "productCategory"
    const val PRODUCT_PRICE: String = "productPrice"
    const val PRODUCT_IMAGE: String = "productImage"
    const val FARMER_ID: String = "farmerID"
    const val CUSTOMER_ID: String = "customerID"
    const val PRODUCT_NO_OF_ORDERS: String = "productNumberOfOrders"
    const val PRODUCT_ORDER_ID="orderID"
    const val ORDER: String = "orders"
    const val QUANTITY: String = "quantity"
    const val CUSTOMER_TO_MY_ORDERS: String = "CustomerToMyOrders"


}